### ISSUE TITLE
成电有没有搞语音的导师和实验室呀

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [ddlBoJack/Speech-Resources#11]
请问成都电子科技大学有没有搞语音的导师呀，今年考研想考成电信通院AWA

**Comment by mortyzhou77** [comment]
> 

有可能有一些年轻的老师，你可以看看教师名录

**Comment by KAWAKO-in-GAYHUB** [comment]
> > 
> 
> 有可能有一些年轻的老师，你可以看看教师名录

我在教师目录里找到了几个有相关研究方向的导师，谢谢您
