### ISSUE TITLE
国内语音公司添加

### ISSUE THREAD

**Issue by yzyouzhang** [ddlBoJack/Speech-Resources#8]
滴滴语音Didi
深声科技deepsound
大象声科Elevoc
声希科技SpeechX
声智科技SoundAI
国音智能speakIn
捷通华声sinovoice
楼氏电子knowles
地平线horizon
清微智能tsingmicro
快商通

**Comment by mortyzhou77** [comment]
很强

**Comment by ddlBoJack** [comment]
You can pull requests if convenient. Many thanks!
